version: '3.8'

services:
  service-app:
    build:
      context: .
      dockerfile: config/Dockerfile
    image: mvc-app
    ports:
      - "9001:9001"
    links:
      - service-mysql
    volumes:
      - '.:/var/www/html'
    env_file:
      - .env
    networks:
      - myapp_network

  service-mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: b2b
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - myapp_network

  service-nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-app
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge

volumes:
  mysql-db:
    driver: local
